hnliving.web/Areas/Cate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Cate.Controllers
{
    public class HomeController : Controller
    {
        // GET: Cate/Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Cate description page.";

            return View();
        }
    }
}

hnliving.web/Areas/H5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.H5.Controllers
{
    public class HomeController : Controller
    {
        // GET: H5/Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Invest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Invest.Controllers
{
    public class HomeController : BaseWebController
    {
        // GET: Invest/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Invest/Controllers/Stock/HomeController.cs
using Lib.Core;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Invest.Controllers.Stock
{
    public class HomeController : BaseWebController
    {
        // GET: Invest/Stock/Home
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// K线
        /// </summary>
        /// <returns></returns>
        public ActionResult KLine(string code)
        {
            ViewBag.Data = "{}";
            if(!string.IsNullOrWhiteSpace(code))
            {
                ResultEntity entity = Lib.Services.Stock.GetDetail(code);
                if(entity.IsSuccess)
                {
                    ViewBag.Data = JsonConvert.SerializeObject(entity.Data);
                }
            }
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult GetDetail(string code)
        {
            ResultEntity result;
            if (string.IsNullOrWhiteSpace(code))
            {
                result = ResultEntity.ParamsError("股票代码不能为空");
            }
            else
            {
                result = Lib.Services.Stock.GetDetail(code);
            }

            string strResult = JsonConvert.SerializeObject(result);
            return Content(strResult);
        }

        public ActionResult GetAverageLine(string code)
        {
            ResultEntity result;
            if (string.IsNullOrWhiteSpace(code))
            {
                result = ResultEntity.ParamsError("股票代码不能为空");
            }
            else
            {
                result = Lib.Services.Stock.GetAverageLine(code);
            }

            string strResult = JsonConvert.SerializeObject(result);
            return Content(strResult);
        }

        public ActionResult GetFormerComplexRights(string code)
        {
            ResultEntity result;
            if (string.IsNullOrWhiteSpace(code))
            {
                result = ResultEntity.ParamsError("股票代码不能为空");
            }
            else
            {
                result = Lib.Services.Stock.GetFormerComplexRights(code);
            }

            string strResult = JsonConvert.SerializeObject(result);
            return Content(strResult);
            //return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMACD(string code)
        {
            ResultEntity result;
            if (string.IsNullOrWhiteSpace(code))
            {
                result = ResultEntity.ParamsError("股票代码不能为空");
            }
            else
            {
                result = Lib.Services.Stock.GetMACD(code);
            }

            string strResult = JsonConvert.SerializeObject(result);
            return Content(strResult);
        }
    }
}

hnliving.web/Areas/Study/Controllers/CivilServant/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Study.Controllers.CivilServant
{
    public class HomeController : Controller
    {
        // GET: Study/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Study/Controllers/Education/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Study.Controllers.Education
{
    public class HomeController : Controller
    {
        // GET: Study/Education/Home
        public ActionResult Index()
        {
            return View("~/Areas/Study/Views/Education/Home/Index.cshtml");
        }
    }
}

hnliving.web/Areas/Study/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Study.Controllers
{
    public class HomeController : Controller
    {
        // GET: Study/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Study/Controllers/Program/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Study.Controllers.Program
{
    public class HomeController : BaseWebController
    {
        const string path = "~/Areas/Study/Views/Program/Home/{0}.cshtml";

        // GET: Study/Program/Home
        public ActionResult Index()
        {
            //System.Diagnostics.StackTrace st = new System.Diagnostics.StackTrace();
            //string viewName = string.Format(path, st.GetFrame(0).GetMethod().Name);

            return View("~/Areas/Study/Views/Program/Home/Index.cshtml");
        }

        // GET: Study/Program/Home
        public ActionResult About()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Tools/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Tools.Controllers
{
    public class HomeController : Controller
    {
        // GET: Tools/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hnliving.web/Areas/Travel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Areas.Travel.Controllers
{
    public class HomeController : Controller
    {
        // GET: Travel/Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Travel description page.";

            return View();
        }
    }
}

hnliving.web/Controllers/AssistantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Controllers
{
    public class AssistantController : BaseWebController
    {
        // GET: Assistant
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Building()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            Response.Status = "404 Not Found...";
            Response.StatusCode = 404;
            return View();
        }

        public ActionResult InternalServerError()
        {
            Response.Status = "500 Internal Server Error";
            Response.StatusCode = 500;
            ViewBag.Description = Response.StatusDescription;
            return View();
        }
    }
}

hnliving.web/Controllers/HomeController.cs
using hnliving.web.Areas.Tools.Models;
using Lib.Core;
using Lib.Services;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hnliving.web.Controllers
{
    public class HomeController : BaseWebController
    {
        // GET: Home
        public ActionResult Index()
        {
            List<UEditorEntity> lstUe = null;
            List<UEditorInfo> lstUei = new List<UEditorInfo>();

            try
            {
                // 获取内容的ID
                int uid = -1;// UserRanks.IsContentEditor(WorkContext.Uid) ? -1 : WorkContext.Uid;

                // 内容
                lstUe = UEditorSer.GetList(new PageEntity(-1, 7), uid);

                // 分类ID名称
                DataTable dtSort = UEditorSer.GetSort(uid);
                
                foreach (UEditorEntity ue in lstUe)
                {
                    DataRow[] drs = dtSort.Select("sid=" + ue.Typeid);
                    string sname = drs.Length > 0 ? drs[0]["sname"].ToString() : "";
                    UEditorInfo uei = new UEditorInfo()
                    {
                        Id = ue.Id,
                        Typename = sname,
                        Title = ue.Title,
                        Create_time = ue.Create_time,
                        Update_time = ue.Update_time,
                        Tag = ue.Tag
                    };
                    lstUei.Add(uei);
                }
                ViewData["lstUei"] = lstUei;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Home/Index" + ex.Message);
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

hnliving.web/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于我们";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <a href=@Url.Action("Building", "Assistant")>
                <img class="d-block w-100" src="~/Images/banner01.jpg" alt="First slide">
            </a>
        </div>
        <div class="carousel-item">
            <a href=@Url.Action("Building", "Assistant")>
                <img class="d-block w-100" src="~/Images/banner02.jpg" alt="Second slide">
            </a>
        </div>
        <div class="carousel-item">
            <a href="~/Study">
                <img class="d-block w-100" src="~/Images/banner03.jpg" alt="Third slide">
            </a>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        @*<span class="sr-only">Previous</span>*@
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        @*<span class="sr-only">Next</span>*@
    </a>
</div>



@*<div class="swiper-container" id="anim">
    <div class="swiper-wrapper">
        <div class="swiper-slide bg-info" style="min-height:200px;">
            <p></p>
            <div class="ani display-3 text-center text-black-50" swiper-animate-effect="rotateIn" swiper-animate-duration="1s" swiper-animate-delay="0.3s">Animate.css</div>
        </div>
        <div class="swiper-slide bg-danger" style="min-height:200px;">
            <p></p>
            <div class="ani display-3 text-center text-v-lgdt-btg" swiper-animate-effect="rubberBand" swiper-animate-duration="1s" swiper-animate-delay="0.3s">Animate.css</div>
        </div>
        <div class="swiper-slide bg-success" style="min-height:200px;">
            <p></p>
            <div class="ani display-3 text-center text-white" swiper-animate-effect="fadeInDown" swiper-animate-duration="1s" swiper-animate-delay="0.3s">Animate.css</div>
        </div>
        <div class="swiper-slide bg-dark" style="min-height:200px;">
            <p></p>
            <div class="ani display-3 text-center text-v-lgdt-vtb" swiper-animate-effect="fadeInUp" swiper-animate-duration="1s" swiper-animate-delay="0.3s">Animate.css</div>
        </div>
    </div>

    <!-- 如果需要分页器 -->
    <div class="swiper-pagination"></div>

    <!-- 如果需要导航按钮 -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- 如果需要滚动条 -->
    <!--<div class="swiper-scrollbar"></div>-->
</div>*@

<div style="height:1800px;"></div>
        尾巴


@section scripts {

    <script>
    
    </script>
}

hnliving.web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "联系我们";
}



<div class="row ml-0 mr-0 mt-5">

    <div class="col-10 offset-1 bg-teal-7">
        <h4>地址：海南省海口市***</h4>
        <hr />

    </div>

</div>

@section scripts {
}

hnliving.web/Views/Home/Index.cshtml
@using hnliving.web.Areas.Tools.Models

@{
    ViewBag.Title = "首页";
    List<UEditorInfo> lstUe = ViewData["lstUei"] as List<UEditorInfo>;
    //System.Collections.Hashtable htSort = ViewData["htSort"] as System.Collections.Hashtable;
}

@section csses {
    <style>
        .bg-img {
            position: absolute;
            left: 0px;
            top: 0px;
            width: 100%;
            height: auto;
            z-index: -999;
        }

        #intro .container{
            opacity:0;
            position:relative;
            top:8rem;
        }

        #dynamic .container{
            opacity:0;
            position:relative;
            top:8rem;
        }

    </style>
}

<div class="swiper-container" id="banner">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <a href=@Url.Action("Building", "Assistant")>
                <img class="d-block w-100" src="~/Images/banner01.jpg" alt="First slide">
            </a>
        </div>
        <div class="swiper-slide">
            <a href=@Url.Action("Building", "Assistant")>
                <img class="d-block w-100" src="~/Images/banner02.jpg" alt="Second slide">
            </a>
        </div>
        <div class="swiper-slide">
            <a href=@Url.Action("Building", "Assistant")>
                <img class="d-block w-100" src="~/Images/banner03.jpg" alt="Third slide">
            </a>
        </div>
    </div>

    <!-- 如果需要分页器 -->
    <div class="swiper-pagination"></div>

    <!-- 如果需要导航按钮 -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- 如果需要滚动条 -->
    @*<div class="swiper-scrollbar"></div>*@
</div>

<!-- 背景图片 -->
<img class="bg-img" id="bg-img" style="" src="~/Images/Films/sd2.jpg" />

@*<div class="mt-5 text-center display-4 text-h-lgdt-vtb rubberBand ani-dur-2">
    欢迎来到
    <span class="hub-lg m-1">琼游记</span>
    翱翔！
</div>*@

<!-- 简介 -->
<div class="bg-lgdt-gtb-9" id="intro">
    <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
            <h1>菜鸟教程</h1>
            <p>学的不仅是技术，更是梦想！！！</p>
            <p>学的不仅是技术，更是梦想！！！</p>
            <p>学的不仅是技术，更是梦想！！！</p>
        </div>
    </div>
</div>

<!-- 调试信息 -->
@*<div class="bg-gray-8" id="debug-info" ondblclick="$(this).hide()" style="position:fixed;bottom:0px;left:0px;color:white;word-break:break-all;z-index:100;font-size:2rem"></div>*@

<!-- 透明占位 -->
<div id="trans-plcholder" style="color:red;height:30rem;"></div>

<!-- 动态 -->
<div class="bg-light-sky-blue-9" id="dynamic">
    <div class="container p-1">
        <div class="col-md-6">
            <div class="d-flex">
                <sapn class="font-size-1-5">动态：</sapn>
                <span class="ml-auto">
                    <a href="/content/list" class="btn btn-outline-danger" role="button">查看更多</a>
                </span>
            </div>
            <table class="table table-striped table-success table-borderless" id="dynamic_list">
                <thead class="thead-dark">
                    <tr>
                        <th align="left">标题</th>
                        <th id="dynamic-sort" width="80" align="center">分类</th>
                        <th id="dynamic-date" width="100" align="center">更新时间</th>
                    </tr>
                </thead>
                <tbody>
                    @if (lstUe != null)
                    {
                        foreach (UEditorInfo uei in lstUe)
                        {
                            <tr> @*<tr onclick="location.href='/content/index?id=@uee.Id';">*@
                                <td><a class="" href="/content/index?id=@uei.Id">@uei.Title</a></td>
                                <td>@uei.Typename</td>
                                <td>@uei.Update_time.ToString("yyyy-MM-dd")</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="bg-teal-7" style="height:700px;">

</div>




@section scripts {
    @*<script src="~/Scripts/Tools/baseFilter.js"></script>*@

    <script>

        var mySwiper = new Swiper('#banner', {
            loop: true, // 循环模式选项

            // 如果需要分页器
            pagination: {
                el: '.swiper-pagination',
                clickable: true,                //--实现小圆点点击
            },

            // 如果需要前进后退按钮
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },

            // 如果需要滚动条
            //scrollbar: {
            //  el: '.swiper-scrollbar',
            //},

            // 自动轮播
            autoplay: {
                delay: 3000,                    // 3秒切换一次
                stopOnLastSlide: false,         // 如果设置为true，当切换到最后一个slide时停止自动切换。（loop模式下无效）。
                disableOnInteraction: false,    // 用户操作swiper之后，是否禁止autoplay.默认为true：停止。
            },
        })


        //var mySwiper = new Swiper('#anim', {
        //    loop: true, // 循环模式选项

        //    // 如果需要分页器
        //    pagination: {
        //        el: '.swiper-pagination',
        //    },

        //    // 如果需要前进后退按钮
        //    navigation: {
        //        nextEl: '.swiper-button-next',
        //        prevEl: '.swiper-button-prev',
        //    },

        //    // 如果需要滚动条
        //    //scrollbar: {
        //    //  el: '.swiper-scrollbar',
        //    //},

        //    on: {
        //        init: function () {
        //            swiperAnimateCache(this); //隐藏动画元素
        //            swiperAnimate(this); //初始化完成开始动画
        //        },
        //        slideChangeTransitionEnd: function () {
        //            swiperAnimate(this); //每个slide切换结束时也运行当前slide动画
        //            //this.slides.eq(this.activeIndex).find('.ani').removeClass('ani'); 动画只展现一次，去除ani类名
        //        }
        //    }
        //})


        // 设置背景图片位置和初始模糊值灰度值
        //$('#bg-img').css('top', $('#head').outerHeight() + $('#banner').outerHeight() + 'px');
        //setBgImg();
        //$('#bg-img').css({
        //    'top': $('#head').outerHeight() + $('#banner').outerHeight() + 'px',
        //    "filter": "blur(10px) grayscale(100%)",
        //    "-webkit-filter": "blur(10px) grayscale(100%)"
        //});

        $().ready(function () {
            // 设置占位DIV
            setPlaceholder();

            // 页面设置
            pageSetting();

            // 窗口改变大小事件
            $(window).resize(function () {
                // 字体适配不同屏幕大小
                //fontAdapt();

                // 设置高度一样(为了顶部菜单占位)
                //setBodyPadding();

                // 设置占位DIV
                setPlaceholder();

                // 页面设置
                pageSetting();
            });

            // 滚动条滚动事件
            $(window).scroll(function () {
                // 页面设置
                pageSetting();
            });

            // 设置占位DIV
            function setPlaceholder() {
                var height = rate > 1 ? $(window).outerHeight() : $(window).outerHeight() * 0.5;
                $('#trans-plcholder').css('height', height + 'px');
            }

            // 页面设置
            function pageSetting() {
                // 设置背景图片
                setBgImg();

                // 设置简介DIV
                setIntro();

                // 设置动态DIV
                setDynamic();
            }

            // 设置背景图片
            function setBgImg() {
                var blurValue = 10;     // 模糊值
                var grayValue = 100;    // 灰度值

                // 获取垂直滚动的距离（scrollTop()是从顶部开始滚动产生的距离）
                var scroll_top = $(document).scrollTop();
                var w_width = $(window).outerWidth();
                var w_height = $(window).outerHeight();
                //var ccc = document.documentElement.clientWidth;

                // 原本的偏移
                var offset = $('#intro').offset().top + $('#intro').outerHeight();

                var a = (50 - rem) * 0.05;
                // 图片偏移
                $('#bg-img').css('top', offset - scroll_top / a + 'px'); // 2.5~3

                // trans-plcholder位置信息
                var top = $('#trans-plcholder').offset().top;
                var height = $("#trans-plcholder").outerHeight();

                var startPos = 0;   // 清晰的开始位置
                var endPos = 0;     // 清晰的结束位置(模糊的开始位置)

                if (rate > 1) { // 宽大于高（电脑）
                    startPos = top;             // 清晰的开始位置
                    endPos = top + 10 * rem;    // 清晰的结束位置(模糊的开始位置)
                } else {        // 宽小于高（手机）
                    startPos = top + 0.3 * height - 0.5 * w_height;     // 清晰的开始位置,这里取遮罩层30%线在浏览器中线的位置
                    endPos = top + height - 0.6 * w_height;             // 清晰的结束位置(模糊的开始位置)
                }

                //$('#debug-info').text('2. startPos=' + startPos + ',endPos=' + endPos + ',top=' + top + ',height=' + height + ',w_height=' + w_height + ',scroll_top=' + scroll_top);

                // 模糊值
                if (scroll_top < startPos) {
                    blurValue = (startPos - scroll_top) / (2 * rem);
                } else if (scroll_top > endPos) {
                    blurValue = (scroll_top - endPos) / (2 * rem);
                } else {
                    blurValue = 0;
                }
                // 灰度值
                if (scroll_top < startPos) {
                    grayValue = (startPos - scroll_top) / (0.5 * rem);
                } else if (scroll_top > endPos) {
                    grayValue = (scroll_top - endPos) / (0.2 * rem);
                } else {
                    grayValue = 0;
                }

                // 设置效果
                $('#bg-img').css({
                    "filter": "blur(" + blurValue + "px) grayscale(" + grayValue + "%)",
                    "-webkit-filter": "blur(" + blurValue + "px) grayscale(" + grayValue + "%)"
                });
                //$('#bg-img').dim(blurValue);
                //$('#bg-img').grayImg(blurValue);
            }

            // 设置简介DIV
            function setIntro() {
                var opacityValue = 100;   // 不透明值

                // 获取垂直滚动的距离（scrollTop()是从顶部开始滚动产生的距离）
                var scroll_top = $(document).scrollTop();
                var w_width = $(window).outerWidth();
                var w_height = $(window).outerHeight();

                // intro位置信息
                var top = $('#intro').offset().top;
                var height = $("#intro").outerHeight();

                // 渐入动画
                if (scroll_top > top - 15 * rem) {
                    $("#intro .container").animate({
                        top: '0rem',
                        opacity: '1'
                    }, 800);
                }

                var startPos = 0;   // 开始变透明的位置
                var endPos = top + height - 0.2 * w_height;     // 完全变透明的位置
                if (rate > 1) { // 宽大于高（电脑）
                    startPos = top + height - 0.5 * w_height;
                } else {        // 宽小于高（手机）
                    startPos = top + height - 0.3 * w_height;
                }

                // 模糊值
                if (scroll_top > startPos) {
                    opacityValue = (endPos - scroll_top) / (endPos - startPos) * 100; //(40 * rem - scroll_top) / (0.2 * rem);
                } else {
                    opacityValue = 100;
                }
                //$('#debug-info').text('1. startPos=' + startPos + ',endPos=' + endPos + ',top=' + top + ',height=' + height + ',w_height=' + w_height + ',scroll_top=' + scroll_top);

                // 设置效果
                $('#intro').css({
                    "filter": "opacity(" + opacityValue + "%)",
                    "-webkit-filter": "opacity(" + opacityValue + "%)"
                });
            }

            // 设置动态DIV
            function setDynamic() {
                // 调整表头宽度
                $('#dynamic-sort').width(4 * rem);
                $('#dynamic-date').width(6 * rem);

                var opacityValue = 0;   // 不透明值

                // 获取垂直滚动的距离（scrollTop()是从顶部开始滚动产生的距离）
                var scroll_top = $(document).scrollTop();
                var w_width = $(window).outerWidth();
                var w_height = $(window).outerHeight();

                // dynamic位置信息
                var top = $('#dynamic').offset().top;
                var height = $("#dynamic").outerHeight();

                var startPos = top - 0.6 * w_height;   // 清晰的开始位置
                var endPos = 0;     // 清晰的结束位置(模糊的开始位置)

                if (rate > 1) { // 宽大于高（电脑）
                    startPos = top - 0.8 * w_height;
                    endPos = top - 0.5 * w_height;
                } else {        // 宽小于高（手机）
                    startPos = top - 0.8 * w_height;
                    endPos = top - 0.5 * w_height;
                }
                //$('#debug-info').text('setDynamic startPos=' + startPos + ',top=' + top + ',height=' + height + ',w_height=' + w_height + ',scroll_top=' + scroll_top);

                // 不透明值
                if (scroll_top > startPos) {
                    opacityValue = (scroll_top - startPos) / (endPos - startPos) * 100;
                } else {
                    opacityValue = 0;
                }

                // 渐入动画
                if (scroll_top > startPos - 0.2 * (endPos - startPos)) {
                    $("#dynamic .container").animate({
                        top: '0rem',
                        opacity: '1'
                    }, 1200);
                }

                // 设置效果
                $('#dynamic').css({
                    "filter": "opacity(" + opacityValue + "%)",
                    "-webkit-filter": "opacity(" + opacityValue + "%)"
                });
            }
        })

    </script>

}